### ISSUE TITLE
Calling asyncio.wait with an empty list raises an error

### ISSUE THREAD

**Issue by renemarc** [amelchio/aiolifx_effects#1]
Hi @amelchio,

Thanks for all your great work on Home Assistant! 😃

For a while I've had my LIFX lights drop off randomly during the day, maybe due to an overly agressive automation, and my error log then contains something like this:

```
2018-08-26 17:05:05 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiolifx_effects/aiolifx_effects.py", line 204, in async_perform
    yield from self.async_play()
  File "/usr/local/lib/python3.6/site-packages/aiolifx_effects/aiolifx_effects.py", line 273, in async_play
    yield from self.conductor.stop(self.participants)
  File "/usr/local/lib/python3.6/site-packages/aiolifx_effects/aiolifx_effects.py", line 104, in stop
    yield from self._stop_nolock(devices)
  File "/usr/local/lib/python3.6/site-packages/aiolifx_effects/aiolifx_effects.py", line 112, in _stop_nolock
    yield from asyncio.wait(tasks)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 304, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.
```

Like with https://github.com/home-assistant/home-assistant/pull/15035, we would need to check that the tasks list is not empty before calling `asyncio.wait`. It is already done in `async_perform`:

https://github.com/amelchio/aiolifx_effects/blob/05fc7c01cefc4066c4c84b3ad821e7a669e2faa9/aiolifx_effects/aiolifx_effects.py#L197-L202

...but `_stop_nolock` should receive the same treatment:

https://github.com/amelchio/aiolifx_effects/blob/05fc7c01cefc4066c4c84b3ad821e7a669e2faa9/aiolifx_effects/aiolifx_effects.py#L108-L112

And maybe other routines too?

**Comment by amelchio** [comment]
Thanks. The intention was that `async_play` would skip the call on line 273 in this case but evidently that does not work :-)

Do you have a testcase to reproduce this? I guess you are stopping the pulse effect with `light.lifx_effect_stop`?

**Comment by renemarc** [comment]
Actually, I don't directly make calls to `light.lifx_effect_stop`; I only use `light.lifx_effect_pulse` to pulse lights one mode/color when a door opens, then another mode/color when it closes in this automation:

https://github.com/renemarc/home-assistant-config/blob/f8fe1294cfefb8901a4f00691689e0bb3e0eac49/automations/notifications/front_door_notify.yaml#L21-L39

It is targeting a group of LIFX devices, whose members may or may not be online (physical switches, WiFi drop issues). It mostly works ...until it doesn't. Maybe the random unavailability of a registered device, or rapid-fire back-to-back calls to `light.lifx_effect_pulse` is causing this?

**Comment by amelchio** [comment]
Okay, so this can happen when the door is open for the duration of the first effect, i.e. one second. Quite a speedy entry :)

I now managed to reproduce it easily by adding some delays to make the risk of failure bigger.
