### ISSUE TITLE
Add more effects to the LIFX library (be used in HA LIFX)

### ISSUE THREAD

**Issue by lubbertkramer** [amelchio/aiolifx_effects#7]
i would like to request to add more effect to this library. I'm not a programmer and would like to support by giving a PR but don't know where to start.  When you have a patreon, tip for coffee or something i would be glad to donate to get those features added into the library when they can be added to the Home Assistant LIFX component

**Effects to be added in top to low:**
Move
Morph (LIFX Tile)
Flame
Breathe

**Comment by amelchio** [comment]
Sorry, I am on hiatus so I am not doing new stuff for HA at the moment (also, I do not have any LIFX Tile to test).

**Comment by lubbertkramer** [comment]
Too bad to hear but enjoy your holiday/break from HA :) 

Just to let you know only the morph is for the LIFX tile all the others can be used on other devices from LIFX -> https://api.developer.lifx.com/docs/move-effect

**Comment by amelchio** [comment]
I believe Morph and Flame are for the LIFX Tile. Move also works on Strip and Beam.

The Breathe effect is actually already supported if you set the `mode` of [`lifx.effect_pulse`](https://www.home-assistant.io/integrations/lifx/#service-lifxeffect_pulse).

**Comment by Djelibeybi** [comment]
Support for Move, Morph and Flame have been merged into Home Assistant.
