### ISSUE TITLE
Open to refactoring and support for firmware effects?

### ISSUE THREAD

**Issue by Djelibeybi** [amelchio/aiolifx_effects#8]
Hey @amelchio. 

I've been working on adding support for themes and firmware effects to the LIFX integration, and I'd like to use this library as the underlying library used by Home Assistant for this. However, given the date of the latest release is over three years ago, I thought it prudent to check if you're still interested in maintaining this library or if you'd prefer not to?

I've already implemented most of the functionality, which included refactoring the library itself to be strictly typed. You can review my work so far in these two branches:

Refactoring/code cleanup: https://github.com/Djelibeybi/aiolifx_effects/tree/refactor-typing
Theme/Firmware effect support: https://github.com/Djelibeybi/aiolifx_effects/tree/add-firmware-effects

There is still debug code littered throughout, which I need to clean up, so these aren't quite yet ready to submit, but they're working _enough_ for you to get a sense of the extent of the changes.

**Comment by amelchio** [comment]
Hello. The library is only used by Home Assistant (as far as I know) so probably we can add you as a maintainer and it will simplify things for everyone?

**Comment by Djelibeybi** [comment]
That works. I'll keep working on smoothing out the edges and then open the PRs as they're ready. I'll probaby submit the refactoring one first, as that also improves performance for multizone devices.
